services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - ./data:/data/db    
  back:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend
  
  front:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - frontend
    depends_on:
      - back
      - db
  proxy:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./ssl/localhost.key:/etc/ssl/private/localhost.key

    depends_on:
      - front

volumes:
  data:

networks:
  frontend:
  backend:

